#!/bin/bash

# e.g. xmonad-x86_64-linux
# bin_name=$(uname -a | awk '{print $1, $13}' | sed -r 's/(.+) (.+)/xmonad-\2-\L\1/')  # I checked in only x86_64 env

if ! (uname -a | grep x86_64 > /dev/null 2>&1) ; then
    echo "./build doesn't support non x86_64 env." > /dev/stderr
    exit 1
fi

cd ~/.xmonad || exit 1

if ! stack build ; then
    echo 'stack build has gone with an unknown reason.' > /dev/stderr
    exit 1
fi

# Like xmonad's --replace

binary=$(find .stack-work/install -type f -name xmonad-config)
if [[ $(echo "$binary" | wc -l) -gt 1 ]] ; then
    echo 'two or more binary found. Please retry after "rm -rf .stack-work".' > /dev/stderr
    exit 1
fi

cp -f "$binary" ./xmonad-x86_64-linux && \
    echo "--replace succeed!"
