name: xmonad-config
version: '0.1.0.0'
synopsis: My XMonad Env
description: Please see README.md
category: Simple
author: aiya000
maintainer: aiya000.develop@gmail.com
copyright: aiya000
license: MIT
homepage: https://github.com/aiya000/xmonad-config

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wno-name-shadowing
  - -Wno-orphans
  - -Wno-type-defaults
  - -Wno-unused-do-bind
  - -Wredundant-constraints
  - -fprint-explicit-kinds
  - -fprint-potential-instances

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - X11
  - base >=4.7 && <5
  - bytestring
  - containers
  - data-default
  - directory
  - easy-file
  - extra
  - file-embed
  - here
  - safe
  - shelly
  - text
  - xmonad
  - xmonad-contrib

executables:
  xmonad-config:
    main: xmonad.hs
    source-dirs: ./.
