flags:
  xmonad-extras:
    with_hint: false
    with_mpd: false
  xmonad-contrib:
    use_xft: false
extra-package-dbs: []
packages:
- '.'
- xmonad/
- xmonad-contrib/
- xmonad-extras/
extra-deps:
- X11-1.8
- alsa-core-0.5.0.1
- alsa-mixer-0.2.0.3
- xmonad-0.13
resolver: lts-7.14
